### ISSUE TITLE
Recht für Nutzer verfügbar machen > Addon nicht für Jeden sichtbar machen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/redaxo_analytics#24]
Es sollte noch eine auswählbare Berechtigung geben, um das Addon (ohne Bereich "Einstellungen") anderen Backend-Nutzern zur Verfügung zu stellen.

Das Addon sollte nicht std.mäßig für alle Nutzer sichtbar sein.

Nur der Admin sollte Einstellungen vornehmen können.

**Comment by TobiasKrais** [comment]
Hab deine Änderungen getestet. Funktioniert. Kannst den Issue schließen.

**Comment by AndiLeni** [comment]
Danke fürs Testen :)
